server:
  port: 8099
  servlet:
    context-path: /demo
    encoding:
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8
    max-connections: 1000
    threads:
      max: 100
      min-spare: 10
    accept-count: 100

spring:
  application:
    name: demo
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?characterEncoding=utf-8&amp;useUnicode=true
    username: postgres
    password: 137hong56962438
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 10
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 30000
#      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: true
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
#  datasource:
#    dynamic:
#      primary: mysql
#      primary: sharding_readwrite_splitting_test_db
#      primary: airbnb_db
#      strict: false
#      datasource:
#        mysql:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC
#          username: root
#          password: 137hong56962438
#        postgresql:
#          driver-class-name: org.postgresql.Driver
#          url: jdbc:postgresql://localhost:5432/postgres?characterEncoding=utf-8&amp;useUnicode=true
#          username: postgres
#          password: 137hong56962438
#        airbnb_db:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/airbnb_db?serverTimezone=UTC
#          username: root
#          password: 137hong56962438
#        sharding_readwrite_splitting_airbnb_db:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://192.168.44.131:3303/sharding_readwrite_splitting_airbnb_db?serverTimezone=UTC
#          username: root
#          password: 137hong56962438
#        sharding_readwrite_splitting_test_db:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://192.168.44.131:3303/sharding_readwrite_splitting_test_db?serverTimezone=UTC
#          username: root
#          password: 137hong56962438
#      type: com.alibaba.druid.pool.DruidDataSource
#      druid:
#        initial-size: 10
#        min-idle: 10
#        max-active: 50
#        max-wait: 10
#        time-between-eviction-runs-millis: 10000
#        min-evictable-idle-time-millis: 30000
#        validation-query: SELECT 1 FROM DUAL
#        test-while-idle: true
#        test-on-borrow: false
#        test-on-return: true
#        pool-prepared-statements: false
#        max-pool-prepared-statement-per-connection-size: 20
#        filters: stat,wall
#  security:
#    user:
#      name: admin
#      password: admin
#      roles: admin

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.bean
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#debezium:
#  name: test_table_listener
#  connector-class: io.debezium.connector.mysql.MySqlConnector
#  offset-storage: org.apache.kafka.connect.storage.FileOffsetBackingStore
#  offset-storage-file-filename: /data/debezium/offsets.dat
#  offset-flush-interval-ms: 60000
#  include-schema-changes: false
#  database-include-list: test
#  table-include-list: test.user_info
#  host: localhost
#  port: 3306
#  username: root
#  password: 137hong56962438
#  server-time-zone: UTC
#  database-allowPublicKeyRetrieval: true
#  database-server-name: test_mysql_instance
#  database-history: io.debezium.relational.history.FileDatabaseHistory
#  database-history-file-filename: /data/debezium/history_offsets.dat
#  database-history-store-only-captured-tables-ddl: true
#  snapshot-mode: schema_only
